config/routes.rb
Deployr::Application.routes.draw do
  devise_for :users
  

  match 'commit' => 'pushes#commit', :as => :commit, :via => ["get", "post"]
  match 'pushes' => 'pushes#index'
  match 'pushes/:id' => 'pushes#show'

  
  resources :servers
  resources :sites do
    resources :gh_pushes
  end

  root :to => "home#index"

end

app/models/gh_push.rb
class GhPush < ActiveRecord::Base
  
  serialize :payload
  
  # Active Record Associations
  belongs_to :repository
  has_many :commits, :dependent => :destroy
  
  def path
    case self.ref
    when "refs/head/staging" then self.repository.site.staging_server.default_path + self.repository.site.staging_path
    when "refs/head/production" then self.repository.site.production_server.default_path + self.repository.site.production_path
    else
      ""
    end
  end
  
  def after_create
    if ["master", "staging", "production"].include? self.short_ref
      self.push_changes
    end
  end
  
  # Helpers
  def short_ref
    self.ref.split("/").pop
  end
  
  # Delayed Jobs
  def push_changes
    self.repository.site.update_working_copy self
    self.repository.site.push_working_copy self unless self.short_ref.eql? "master"
  end
  handle_asynchronously :push_changes
end

app/controllers/gh_pushes_controller.rb
class GhPushesController < ApplicationController
  # GET /gh_pushes
  # GET /gh_pushes.xml
  def index
    @gh_pushes = GhPush.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gh_pushes }
    end
  end

  # GET /gh_pushes/1
  # GET /gh_pushes/1.xml
  def show
    @gh_push = GhPush.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gh_push }
    end
  end
end

app/helpers/gh_pushes_helper.rb
module GhPushesHelper
end

app/views/gh_pushes/index.html.erb
<h1>Listing gh_pushes</h1>

<table>
  <tr>
    <th>Site</th>
    <th>Payload</th>
    <th>Ref</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gh_pushes.each do |gh_push| %>
  <tr>
    <td><%= gh_push.site_id %></td>
    <td><%= gh_push.payload %></td>
    <td><%= gh_push.ref %></td>
    <td><%= link_to 'Show', gh_push %></td>
    <td><%= link_to 'Edit', edit_gh_push_path(gh_push) %></td>
    <td><%= link_to 'Destroy', gh_push, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gh push', new_gh_push_path %>

app/views/gh_pushes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Site:</b>
  <%= @gh_push.site_id %>
</p>

<p>
  <b>Payload:</b>
  <%= @gh_push.payload %>
</p>

<p>
  <b>Ref:</b>
  <%= @gh_push.ref %>
</p>


<%= link_to 'Edit', edit_gh_push_path(@gh_push) %> |
<%= link_to 'Back', gh_pushes_path %>