config/routes.rb
Deployr::Application.routes.draw do
  devise_for :users
  

  match 'commit' => 'pushes#commit', :as => :commit, :via => ["get", "post"]
  match 'pushes' => 'pushes#index'
  match 'pushes/:id' => 'pushes#show'

  
  resources :servers
  resources :sites do
    resources :gh_pushes
  end

  root :to => "home#index"

end

app/models/server.rb
class Server < ActiveRecord::Base  
  
  has_many :production_sites, :class_name => "Site", :foreign_key => "production_server_id"
  has_many :staging_sites, :class_name => "Site", :foreign_key => "staging_server_id"
  
  # Fix name issues with link_to and form_for
  def self.model_name
    name = "server"
    name.instance_eval do
      def plural;   pluralize;   end
      def singular; singularize; end
      def human;    singularize; end # only for Rails 3
    end
    return name
  end
  
  # Select options containing all server descendants
  def self.select_options
    descendants.collect{ |c| [c.select_name, c.to_s] }
  end
  
  # Human friendly name
  def self.select_name
    "Generic Server"
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.xml
  def index
    @servers = Server.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.xml
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.xml
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.xml
  def create
    @server = Server.new(params[:server])
    @server.update_attribute(:type, params[:server][:type])

    respond_to do |format|
      if @server.save
        format.html { redirect_to(@server, :notice => 'Server was successfully created.') }
        format.xml  { render :xml => @server, :status => :created, :location => @server }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.xml
  def update
    @server = Server.find(params[:id])
    @server.update_attribute(:type, params[:server][:type])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to(@server, :notice => 'Server was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @server.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.xml
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to(servers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hostname %><br />
    <%= f.text_field :hostname %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :type, Server.select_options %>
  </div>
  <div class="field">
    <%= f.label :port %><br />
    <%= f.number_field :port, :min => 21, :max => 22, :step => 1 %>
  </div>
  <div class="field">
    <%= f.label :default_path %><br />
    <%= f.text_field :default_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <tr>
    <th>Hostname</th>
    <th>Username</th>
    <th>Password</th>
    <th>Type</th>
    <th>Port</th>
    <th>Default path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @servers.each do |server| %>
  <tr>
    <td><%= server.hostname %></td>
    <td><%= server.username %></td>
    <td><%= "*" * server.password.length %></td>
    <td><%= server.class.select_name %></td>
    <td><%= server.port %></td>
    <td><%= server.default_path %></td>
    <td><%= link_to 'Show', server %></td>
    <td><%= link_to 'Edit', edit_server_path(server) %></td>
    <td><%= link_to 'Destroy', server, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<h1><%=h @server.hostname %></h1>

<p>
  <b>Hostname:</b>
  <%= @server.hostname %>
</p>

<p>
  <b>Username:</b>
  <%= @server.username %>
</p>

<p>
  <b>Password:</b>
  <%= "*" * @server.password.length %>
</p>

<p>
  <b>Type:</b>
  <%= @server.class.select_name %>
</p>

<p>
  <b>Port:</b>
  <%= @server.port %>
</p>

<p>
  <b>Default path:</b>
  <%= @server.default_path %>
</p>

<p>
  <b>Staging Sites:</b>
  <ul>
    <% if @server.staging_sites.length == 0 -%>
      <li>No sites here!</li>
    <% end -%>
    <% @server.staging_sites.each do |site| -%>
      <li><%= link_to "dev.#{site.domain}", site %></li>
    <% end -%>
  </ul>
  <%= link_to "Add a Site", :controller => "sites", :action => :new %>
</p>

<p>
  <b>Production Sites:</b>
  <ul>
    <% if @server.production_sites.length == 0 -%>
      <li>No sites here!</li>
    <% end -%>
    <% @server.production_sites.each do |site| -%>
      <li><%= link_to "www.#{site.domain}", site %></li>
    <% end -%>
  </ul>
  <%= link_to "Add a Site", :controller => "sites", :action => :new %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>