config/routes.rb
Deployr::Application.routes.draw do
  devise_for :users
  

  match 'commit' => 'pushes#commit', :as => :commit, :via => ["get", "post"]
  match 'pushes' => 'pushes#index'
  match 'pushes/:id' => 'pushes#show'

  
  resources :servers
  resources :sites do
    resources :gh_pushes
  end

  root :to => "home#index"

end

app/models/site.rb
class Site < ActiveRecord::Base
  
  # Associations
  belongs_to :staging_server, :class_name => "Server"
  belongs_to :production_server, :class_name => "Server"
  has_many :gh_pushes, :through => :repository
  has_one :repository, :dependent => :destroy
  
  # Validations
  
  
  # Callbacks
  
  def after_create
    self.setup_repo
  end
  
  def after_destroy
    self.destroy_repo
  end
  
  # Helper methods
  
  def working_directory
    "#{DEPLOYR['working_directory']}/#{self.id}"
  end
  
  def git_repo
    require 'uri'
    "git@github.com:#{URI.parse(self.gh_url).path[1..-1]}.git"
  end
  
  def has_ref? ref
    repo = Grit::Repo.new(self.working_directory)
    local_branch = repo.branches.find {|branch| branch.name == ref}
    
    local_branch.nil?
  end
  
  # Delayed Jobs
  
  def setup_repo
    # Create the working directory
    FileUtils.mkdir(self.working_directory)
    
    # Clone the git repo into the working directory
    command = "git clone #{self.git_repo} #{self.working_directory}"
    output = system(command)
  end
  handle_asynchronously :setup_repo
  
  def destroy_repo(site)
    FileUtils.remove_dir(site.working_directory)
  end
  handle_asynchronously :destroy_repo
  
  def update_working_copy(push)
    if self.has_ref? push.short_ref
      command = "cd #{self.working_directory}; git pull; git checkout -t 'origin/#{push.short_ref}'"
      puts command
      output = system(command) 
    else
      command = "cd #{self.working_directory}; git checkout #{push.short_ref}; git pull origin #{push.short_ref}"
      output = system(command)
    end
  end
  
  def push_working_copy(push)
    # Make sure the working directory has the appropriate source
    command = "cd #{self.working_directory}; git checkout #{push.short_ref}"
    output = system(command)
    
    # Retrieve the server
    server = nil
    if push.short_ref.eql? "staging"
      server = self.staging_server
    elsif push.short_ref.eql? "production"
      server = self.production_server
    end
    
    # Contact the driver and perform the appropriate actions
    if not server.nil?
      server.connect
      push.commits.each do |commit|
        # Remove the appropriate files
        commit.removed.each do |path|
          server.remove_file path
        end unless commit.removed.nil?
        
        # Modify the appropriate files
        commit.modified.each do |path|
          server.modify_file path, "#{self.working_directory}#{path}"
        end unless commit.modified.nil?
        
        # Add the appropriate files
        commit.added.each do |path|
          server.add_file path, "#{self.working_directory}#{path}"
        end unless commit.added.nil?
      end
      server.disconnect
    end
  end
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.xml
  def index
    @sites = Site.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.xml
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.xml
  def new
    @site = Site.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.xml
  def create
    @site = Site.new(params[:site])
    
    respond_to do |format|
      if @site.save
        format.html { redirect_to(@site, :notice => 'Site was successfully created.') }
        format.xml  { render :xml => @site, :status => :created, :location => @site }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.xml
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to(@site, :notice => 'Site was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.xml
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to(sites_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain, :placeholder => "example.com" %>
  </div>
  <div class="field">
    <%= f.label :gh_url, "Github URL" %><br />
    <%= f.text_field :gh_url, :placeholder => "http://wwww.github.com/teamcolab/deployr" %>
  </div>
  <div class="field">
    <%= f.label :staging_server_id %><br />
    <%= f.collection_select :staging_server_id, Server.all, :id, :hostname, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :production_server_id %><br />
    <%= f.collection_select :production_server_id, Server.all, :id, :hostname, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :staging_path %><br />
    <%= f.text_field :staging_path, :placeholder => "/dev" %>
  </div>
  <div class="field">
    <%= f.label :production_path %><br />
    <%= f.text_field :production_path, :placeholder => "/www" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Domain</th>
    <th>Staging server</th>
    <th>Production server</th>
    <th>Staging path</th>
    <th>Production path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.domain %></td>
    <td><%= site.staging_server.hostname %></td>
    <td><%= site.production_server.hostname %></td>
    <td><%= site.staging_path %></td>
    <td><%= site.production_path %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<h1><%=h @site.domain %></h1>

<p>
  <b>Domain:</b>
  <%= @site.domain %>
</p>

<p>
  <b>Github URL:</b>
  <%= @site.gh_url %>
</p>

<p>
  <b>Staging server:</b>
  <%= link_to @site.staging_server.hostname, @site.staging_server %>
</p>

<p>
  <b>Production server:</b>
  <%= link_to @site.production_server.hostname, @site.production_server %>
</p>

<p>
  <b>Staging path:</b>
  <%= @site.staging_server.default_path + @site.staging_path %>
</p>

<p>
  <b>Production path:</b>
  <%= @site.production_server.default_path + @site.production_path %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>